language: ruby
branches:
  only:
    - master
services:
  - docker

before_install:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
- docker build --no-cache -t cloudqq/electron-docker .
- docker tag cloudqq/electron-docker:latest cloudqq/electron-docker:v1
- docker push cloudqq/electron-docker